### PR TITLE
feat: Nomad Local Environment Full Documentation Addition

### PR DESCRIPTION
**Pull request by xBalbinus**
## Motivation

Currently, the NomadEnv does not have any documentation. This PR adds related documentation and a few small modifications on the Nomad Environment.

## Solution

- Wrote and attached the Local Environment docs as a link in the readme (unsure if I should just include the whole markdown in the readme.

## PR Checklist

- [x] Added Tests (not required, peer feedback required)
- [x] Updated Documentation
- [x] Updated CHANGELOG.md for the appropriate package

### CODE REVIEW

**Comment by prestwich** [comment]
is this work current?

**Comment by xBalbinus** [comment]
I think this has been somewhat deprioritized, but this indeed still needs
review and approval (content ready).

**Comment by odyslam** [comment]
Shouldn't the documentation be added to our docs website?

**Comment by xBalbinus** [comment]
Yeah, most likely - I'll move this PR to the docs repo then.

**Comment by prestwich** [comment]
@xBalbinus can this be closed?

**Comment by xBalbinus** [comment]
Yeah, closable - this has been somewhat deprioritized. I've added the
original document to Clickup so we're good.

**Pull request closed without merging**
