### PR TITLE
fix: expose bridge contract accountant types

### PR DESCRIPTION
**Pull request by ErinHales**
Expose types

## PR Checklist

- [ ] Added Tests
- [ ] Updated Documentation
- [x] Updated CHANGELOG.md for the appropriate package

### CODE REVIEW

**Review by prestwich — APPROVED** [review]

**Review by Imti — APPROVED** [review]
🧩

**Comment by prestwich** [comment]
needs rebase on main but good 2 go

**Comment by ErinHales** [comment]
Dang I just rebased...

**Comment by prestwich** [comment]
lmao sorry we're doing a bunch of PRs today 😅

**Pull request merged**
