### PR TITLE
[DONTMERGE] config, verification, and gov transactions for xdai + point-to-point

### PR DESCRIPTION
**Pull request by anna-carroll**
## Motivation

We want to deploy Nomad to Gnosis Chain (xDai)

## Solution

Deploy Nomad to Gnosis Chain (xDai)! 
Save the updated config, governance actions, and verification for posterity + peer review.

## PR Checklist

- [ ] Added Tests
- [ ] Updated Documentation
- [ ] Updated CHANGELOG.md for the appropriate package

### CODE REVIEW

**Comment by anna-carroll** [comment]
**Governance transactions in this PR** 

## Milkomeda
Enroll xDai to Milkomeda
- [ ] enroll BridgeRouter
- [ ] enroll GovernanceRouter 
- [ ] enroll Replica
- [ ] enroll Watchers

Enroll Moonbeam to Milkomeda
- [ ] enroll BridgeRouter
- [ ] enroll GovernanceRouter 
- [ ] enroll Replica
- [ ] enroll Watchers

Enroll Ethereum
- [ ] enroll Watchers

## Moonbeam
Enroll xDai to Moonbeam
- [ ] enroll BridgeRouter
- [ ] enroll GovernanceRouter 
- [ ] enroll Replica
- [ ] enroll Watchers

Enroll Milkomeda to Moonbeam
- [ ] enroll BridgeRouter
- [ ] enroll GovernanceRouter 
- [ ] enroll Replica
- [ ] enroll Watchers

## Ethereum

Enroll xDai
- [ ] enroll BridgeRouter
- [ ] enroll GovernanceRouter 
- [ ] enroll Replica
- [ ] enroll Watchers

**Comment by anna-carroll** [comment]
is the order of domain/address switched between the xAppConnectionManager (Replica, Watchers) and the xApps (GovernanceRouter, BridgeRouter)? yes. 
was this intentional? no.

**Comment by anna-carroll** [comment]
I've verified that
- there are 9 txs for milkomeda
- there are 8 txs for moonbeam 
- there are 4 txs for ethereum 

(as expected) 

I have also gone through and verified the `to`, function selector, and params for each transaction. The process of manually gut-checking the bytecode is pretty manual, but from my best-effort attempts to verify the contents, these governance transactions are correct.

**Comment by kekonen** [comment]
Manually went through my own style, checked every `to`, function hash, `domain` argument and target for every 21 transactions.

All matches Hurray :)

**Comment by prestwich** [comment]
governance is send it 👍

**Comment by anna-carroll** [comment]
tx executed: https://etherscan.io/tx/0xc3e14b1b56472ec12f7d6141c77de0f29527cfa8cfc70dfb661ab4ae4553d286#eventlog

**Pull request closed without merging**
